version: '3.9'
services:
  linkedout-frontend:
    image: abzed/linkedout-frontend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - linkedout-backend

  linkedout-backend:
    image: abzed/linkedout-backend
    ports:
      - "3000:3000"
    restart: always