apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linkedout-backend
    version: v1
  name: linkedout-backend
  namespace: default

spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: linkedout-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: linkedout-backend
        version: v1
    spec:
      containers:
      - image: abzed/linkedout-backend
        imagePullPolicy: IfNotPresent
        name: linkedout-backend
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 200m
            memory: 1024Mi
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: linkedout-backend
  name: linkedout-backend
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: linkedout-backend
  sessionAffinity: None
  type: LoadBalancer